#!/usr/bin/env python
# 
# run all of the examples
#
# $Id$

Files = (
    "arrowPlot.py",
    "arrowPlot2D.py",
    "arrowPlot3D.py",
    "ballPlot.py",
    "contourPlot.py",
    "contourPlotMovie.py",
    "meshPlot.py",
    "multiCurvePlot.py",
    "offsetLinePlot.py",
    "offsetPlot.py",
    "seismicOffsetPlot.py",
    "seismicOffsetPlot2.py",
    "seismicOffsetPlot3.py",
    "simpleLinePlot.py",
    "simplePlotMovie.py",
    "singleArrayLinePlot.py",
    "surfaceAndContourPlot.py",
    "surfacePlot.py",
    "scatterPlot.py",
    "scatterPlot3D.py",
)

print "Running all examples"

import os
for file in Files:
    print "Running %s" % file
    os.system("python %s" % file)

# vim: expandtab shiftwidth=4:
