#!/usr/bin/env python
# 
# run all of the examples
#
# $Id$

Files = (
    "arrowPlot.py",
    "arrowPlot2D.py",
    "arrowPlot3D.py",
    "ballPlot.py",
    "contourPlot.py",
    "contourPlotMovie.py",
    "isosurfacePlot.py",
    "meshPlot.py",
    "multiCurvePlot.py",
    "offsetLinePlot.py",
    "offsetPlot.py",
    "seismicOffsetPlot.py",
    "seismicOffsetPlot2.py",
    "seismicOffsetPlot3.py",
    "simpleLinePlot.py",
    "simplePlotMovie.py",
    "singleArrayLinePlot.py",
    "surfaceAndContourPlot.py",
    "surfacePlot.py",
    "scatterPlot.py",
    "scatterPlot3D.py",
)

print "Running all examples"

import os
err = open("runall.errs", "w")
for file in Files:
    print ""
    print 70*"#"
    print "Running %s" % file
    print 70*"#"
    print ""
    result = os.system("python %s" % file)
    if result != 0:
        print "Error running example script: %s" % file
        err.write("Error running example script: %s\n" % file)

err.close()

# vim: expandtab shiftwidth=4:
