#!/usr/bin/env python
# 
# run all of the examples
#
# $Id$

Files = (
    "arrowPlotExample.py",
    "arrowPlotExample2.py",
    "ballPlotExample.py",
    "contourPlotExample.py",
    "contourPlotMovieExample.py",
    "meshPlotExample.py",
    "multiCurvePlotExample.py",
    "offsetLinePlotExample.py",
    "offsetPlotExample.py",
    "seismicOffsetPlotExample.py",
    "seismicOffsetPlotExample2.py",
    "seismicOffsetPlotExample3.py",
    "simpleLinePlot.py",
    "simplePlotMovieExample.py",
    "singleArrayLinePlot.py",
    "surfaceAndContourPlotExample.py",
    "surfacePlotExample.py",
    "scatterPlotExample.py",
    "scatterPlot3DExample.py",
)

print "Running all examples"

import os
for file in Files:
    print "Running %s" % file
    os.system("python %s" % file)

# vim: expandtab shiftwidth=4:
