# Copyright (C) 2004-2005 Paul Cochrane
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

# $Id$

## @file render.py

"""
This is the file for the Renderer class
"""

# generic imports
from pyvisi.renderers.gnuplot.common import debugMsg, _gnuplot4
from pyvisi.renderer import Renderer as BaseRenderer

__revision__ = '$Revision'

class Renderer(BaseRenderer):
    """
    A generic object holding a renderer of a Scene().
    """

    def __init__(self):
        """
        Initialisation of Renderer() class
        """
        debugMsg("Called Renderer.__init__()")
        BaseRenderer.__init__(self)

        # initialise some attributes
        self.renderWindowWidth = 640
        self.renderWindowHeight = 480

        # initialise the evalstack
        self._evalStack = ""

        # initialise the renderer module

        self.addToEvalStack("# Renderer.__init__()")
        self.addToEvalStack("import Gnuplot")
        if (_gnuplot4):
            evalString = "Gnuplot.GnuplotOpts.gnuplot_command="
            evalString += "'/usr/local/bin/gnuplot4'"
            self.addToEvalStack(evalString)
        # Gnuplot package needs Numeric package
        self.addToEvalStack("from Numeric import *")

        # need to add a check here to see if the Numeric module has been
        # imported, and if not, throw an error.  The hard part about this
        # is that it has to be done inside the renderer thread, and so
        # is part of the autogenerated code.

        self.addToEvalStack("_gnuplot = Gnuplot.Gnuplot()")

# vim: expandtab shiftwidth=4:
