# Copyright (C) 2004 Paul Cochrane
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

# $Id$

## @file render.py

"""
This is the file for the Renderer class
"""

# generic imports
from common import _debug, rendererName
from pyvisi.renderer import Renderer as BaseRenderer

class Renderer(BaseRenderer):
    """
    A generic object holding a renderer of a Scene().
    """

    def __init__(self):
        """
        Initialisation of Renderer() class
        """
        if _debug: print "\t%s: Called Renderer.__init__()" % rendererName

        # initialise some attributes
        self.renderWindowWidth = 640
        self.renderWindowHeight = 480

        # initialise the evalstack
        self._evalStack = ""

        # initialise the renderer module

        self.addToEvalStack("# Renderer.__init__\n")
        self.addToEvalStack("import Gnuplot\n")

        # need to add a check here to see if the Numeric module has been
        # imported, and if not, throw an error.  The hard part about this
        # is that it has to be done inside the renderer thread, and so
        # is part of the autogenerated code.

        self.addToEvalStack("_gnuplot = Gnuplot.Gnuplot()\n")


        return

# vim: expandtab shiftwidth=4:
