#!/usr/bin/env python
# 
# run all of the examples
#
# $Id$

Files = (
    "arrowPlotExample.py",
    "arrowPlotExample2.py",
    "contourPlotExample.py",
    "contourPlotMovieExample.py",
    "multiCurvePlotExample.py",
    "simplePlotExample.py",
    "simplePlotMovieExample.py",
    "singleArrayPlotExample.py",
    "surfaceAndContourPlotExample.py",
    "surfacePlotExample.py",
    "scatterPlotExample.py",
    "scatterPlot3DExample.py",
)

print "Running all examples"

import os
for file in Files:
    print "Running %s" % file
    os.system("python %s" % file)

# vim: expandtab shiftwidth=4:
